title: Customize.css
email: galulex@gmail.com
description: >
  customize.css provides you with the base styling for your application and gives you ability to easily customize the look of your app.
  The main advantage of this lib that you don't have to overwrite styles you can just set it.
  Another advantage is that all inputs, checkboxes, radio buttons, select boxes have the same look and behaviour in all browsers.
  Also you can change the look of select or checkbox by setting several sass maps.
  This is the engine that supports themes so developers are able to share themes between each other.
baseurl: 'http://activebridge.github.io/customize.css'
url: 'http://activebridge.github.io/customize.css'
github_username:  galulex

# Build settings
markdown: kramdown
